# Copyright  : Copyright (C) 2017 ~ 2035 SupersocksR ORG. All rights reserved.
# Description: PPP PRIVATE NETWORK™ 2 LINUX BUILD SCRIPT CROSS.(X) 1.0.0 VERSION.
# Author     : Kyou.
# Date-Time  : 2024/02/14

name: PPP PRIVATE NETWORK™ 2 LINUX BUILD SCRIPT CROSS.(X) 1.0.0 VERSION.
on:
on:
  watch:
    types: started


jobs:
  build:
    name: Run on CentOS 7
    runs-on: ubuntu-latest
    container:
      image: "centos:7"  # 需要运行的容器镜像（参考 docker hub）
        arch: [amd64] # ${{ runner.arch }}
        platform: 
          - linux/amd64
    

    runs-on: ${{ matrix.os }}
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
    - name: Checkout openppp2
      run: git clone https://github.com/liulilittle/openppp2.git openppp2 # uses: actions/checkout@v2

    - name: Checkout 3rd
      run: |
        git clone https://github.com/liulilittle/openppp2-ubuntu-3rd-environment.git 3rd

    - name: Get number of cpus
      run: |
        echo ::set-env name=ncpu::$(nproc)

    - name: Set THIRD_PARTY_LIBRARY_DIR environment variables
      run: |
        case ${{ matrix.platform }} in
          linux/amd64)
            echo ::set-env name=THIRD_PARTY_LIBRARY_DIR::${GITHUB_WORKSPACE}/3rd/amd64
            ;;

          *)
            echo "Unsupported platform: ${{ matrix.platform }}"
            exit 1
            ;;
        esac

    - name: Select compiler
      run: |
        case ${{ matrix.platform }} in
          linux/amd64)
            echo ::set-env name=PLATFORM_LD::ld
            echo ::set-env name=PLATFORM_CC::gcc
            echo ::set-env name=PLATFORM_CXX::g++
            ;;

          *)
            echo "Unsupported platform: ${{ matrix.platform }}"
            exit 1
            ;;
        esac

    - name: Print environment variables
      run: echo "ncpu:$ncpu, PLATFORM_LD:$PLATFORM_LD, PLATFORM_CC:$PLATFORM_CC, PLATFORM_CXX:$PLATFORM_CXX, THIRD_PARTY_LIBRARY_DIR:$THIRD_PARTY_LIBRARY_DIR"

    - name: Replace THIRD_PARTY_LIBRARY_DIR in CMakeFiles.txt.
      run: |
        cd openppp2
        sed -i 's/SET(THIRD_PARTY_LIBRARY_DIR \/root\/dev)/SET(THIRD_PARTY_LIBRARY_DIR $ENV{THIRD_PARTY_LIBRARY_DIR})/' CMakeLists.txt

    - name: Install dependencies
      run: |
        sudo yum update -y
        sudo yum install git build-essential lrzsz zip unzip libkrb5-dev libicu-dev screen iftop openssl libssl-dev libunwind8 iftop net-tools gcc-multilib gdb clang cmake curl wget autoconf -y

    - name: Install cross compiler
      run: |
        case ${{ matrix.platform }} in
          linux/amd64)
            sudo yum install gcc g++ -y
            ;;
          *)
            echo "Unsupported platform: ${{ matrix.platform }}"
            exit 1
            ;;
        esac

    - name: Build openppp2
      run: |
        PLATFORM=${{ matrix.platform }}
        PLATFORM=${PLATFORM//\//-}

        cd openppp2
        mkdir -p build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=$PLATFORM_CC -DCMAKE_CXX_COMPILER=$PLATFORM_CXX -DCMAKE_LINKER=$PLATFORM_LD
        make -j $ncpu
        cd ../bin

        ARTIFACT_NAME=openppp2-$PLATFORM.zip
        zip -r $ARTIFACT_NAME ppp
        echo "ARTIFACT_NAME=$ARTIFACT_NAME" >> $GITHUB_ENV
      
    - name: Archive openppp2
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: openppp2/bin/${{ env.ARTIFACT_NAME }}
